async (page) => {
  if (!/^http:\/\/(localhost|127\.0\.0\.1):8503\/#\/new$/.test(page.url())) throw new Error("仅允许在8503离线验收入口运行，不能删除正式历史。");
  const output = "output/playwright/";
  const resume = "示例求职者，示例学校本科。参与需求记录整理，制作并交付3份项目说明。";
  const jd = "产品助理：整理需求文档，协助项目推进与验收。";
  const results = [];
  const verify = (condition, message) => { if (!condition) throw new Error(message); results.push(message); };
  const overflow = () => page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  await page.reload();
  await page.getByRole("button", { name: "开始分析 →", exact: true }).click();
  verify(await page.locator("#api-key-error").textContent() !== "", "空Key有提示");
  verify(await page.locator("#resume-error").textContent() !== "", "空简历有提示");
  verify(await page.locator("#jd-error").textContent() !== "", "空JD有提示");
  await page.locator('[data-input="resume"][data-mode="text"]').click();
  await page.locator("#api-key").fill("offline-test-key");
  await page.locator("#resume-text").fill(resume);
  await page.locator("#jd-text").fill(jd);
  verify(await page.locator("#api-key-error").textContent() === "", "修正Key后立即清除错误提示");
  verify(await page.locator("#jd-error").textContent() === "", "修正JD后立即清除错误提示");
  await page.getByRole("link", { name: "历史记录", exact: true }).click();
  await page.getByText("你的第一份分析，从这里开始。", { exact: true }).waitFor();
  verify(await page.locator(".history-table").count() === 0, "空历史不显示记录行");
  await page.getByRole("link", { name: "新建分析", exact: true }).first().click();
  verify(await page.locator("#resume-text").inputValue() === resume, "切换页面保留简历草稿");
  verify(await page.locator("#jd-text").inputValue() === jd, "切换页面保留JD草稿");
  await page.screenshot({ path: output + "new-analysis.png", fullPage: true });
  await page.getByRole("button", { name: "开始分析 →", exact: true }).click();
  await page.getByRole("heading", { name: "岗位匹配分析", exact: true }).waitFor({ timeout: 15000 });
  verify(await page.locator(".question").count() === 10, "展示10道折叠面试题");
  await page.locator(".question summary").first().click();
  verify(await page.locator(".question").first().getAttribute("open") !== null, "面试答案可以展开");
  verify(await page.locator("#result-content").textContent().then(text => text.includes("【文档交付】")), "优化建议保留四字能力标签");
  for (const width of [1366, 1440, 1920, 390]) {
    await page.setViewportSize({ width, height: 900 });
    verify(!(await overflow()), `${width}px结果页没有整页横向溢出`);
  }
  await page.screenshot({ path: output + "result-mobile.png", fullPage: true });
  verify(await page.locator(".result-actions>.button").last().evaluate(element => element.clientWidth > 300), "手机结果页下一步按钮完整展示");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: output + "result-analysis.png", fullPage: true });
  await page.getByRole("link", { name: "查看学习计划与下载", exact: false }).click();
  await page.getByRole("heading", { name: "30天学习计划", exact: true }).waitFor();
  verify(await page.locator(".week").count() === 4, "学习计划按四周组织");
  verify(await page.getByRole("link", { name: "下载岗位定制简历", exact: false }).count() === 0, "非DOCX不提供Word下载");
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("link", { name: "下载完整Markdown报告", exact: false }).click();
  const download = await downloadPromise;
  verify(download.suggestedFilename().includes("产品助理"), "报告下载按岗位命名");
  await download.saveAs(output + "browser-report.md");
  await page.screenshot({ path: output + "result-prepare.png", fullPage: true });
  await page.getByRole("link", { name: "返回匹配分析", exact: false }).click();
  await page.getByRole("heading", { name: "岗位匹配分析", exact: true }).waitFor();
  await page.getByRole("link", { name: "历史记录", exact: true }).click();
  await page.locator(".history-table tbody tr").first().waitFor();
  const count = await page.locator(".history-table tbody tr").count();
  await page.locator("[data-delete]").first().click();
  verify(await page.locator("#delete-dialog").isVisible(), "删除前显示不可恢复确认弹窗");
  await page.getByRole("button", { name: "取消", exact: true }).click();
  verify(await page.locator(".history-table tbody tr").count() === count, "取消删除不改变记录");
  await page.screenshot({ path: output + "history.png", fullPage: true });
  await page.getByRole("link", { name: "查看记录", exact: true }).first().click();
  await page.getByRole("heading", { name: "岗位匹配分析", exact: true }).waitFor();
  verify(!(await page.locator(".spinner").count()), "历史结果直接显示完成状态");
  await page.getByRole("link", { name: "新建分析", exact: true }).click();
  await page.locator('[data-input="resume"][data-mode="file"]').click();
  await page.locator("#resume-file").setInputFiles("output/playwright/sample-resume.docx");
  await page.getByRole("button", { name: "开始分析 →", exact: true }).click();
  await page.getByRole("heading", { name: "岗位匹配分析", exact: true }).waitFor({ timeout: 15000 });
  await page.getByRole("link", { name: "查看学习计划与下载", exact: false }).click();
  const wordPromise = page.waitForEvent("download");
  await page.getByRole("link", { name: "下载岗位定制简历", exact: false }).click();
  const word = await wordPromise;
  await word.saveAs(output + "browser-tailored-resume.docx");
  verify(word.suggestedFilename().endsWith(".docx"), "DOCX定制简历可以下载");
  await page.getByRole("link", { name: "历史记录", exact: true }).click();
  await page.locator(".history-table tbody tr").first().waitFor();
  for (let remaining = await page.locator(".history-table tbody tr").count(); remaining > 0; remaining--) {
    await page.locator("[data-delete]").first().click();
    await page.getByRole("button", { name: "永久删除", exact: true }).click();
    if (remaining > 1) await page.waitForFunction(expected => document.querySelectorAll(".history-table tbody tr").length === expected, remaining - 1);
    else await page.getByText("你的第一份分析，从这里开始。", { exact: true }).waitFor();
  }
  verify(await page.locator(".history-table").count() === 0, "确认删除最后一条测试记录后进入空状态");
  await page.getByRole("link", { name: "新建分析", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  verify(!(await overflow()), "390px新建页没有整页横向溢出");
  await page.screenshot({ path: output + "new-mobile.png", fullPage: true });
  await page.locator("#api-key").focus();
  await page.keyboard.press("Tab");
  verify(await page.locator("#toggle-key").evaluate(element => element === document.activeElement), "输入框可按Tab到达显示按钮");
  await page.emulateMedia({ reducedMotion: "reduce" });
  verify(await page.locator(".primary").first().evaluate(element => getComputedStyle(element).transitionDuration === "0s"), "遵循减少动画偏好");
  await page.emulateMedia({ reducedMotion: "no-preference" });
  await page.setViewportSize({ width: 1440, height: 1000 });
  return results;
}
